# Generated gRPC service stubs
# This module would normally be generated by grpc_tools.protoc

import grpc
from typing import Iterator, AsyncIterator

class SolverServicer:
    """Servicer class for Solver service - implement SubmitSolve and GetSolveStatus"""

    def __init__(self):
        pass

    def SubmitSolve(self, request, context):
        """Submit a new solve job"""
        raise NotImplementedError("Implement in subclass")

    def GetSolveStatus(self, request, context):
        """Get the status of a solve job"""
        raise NotImplementedError("Implement in subclass")

    def CalculateICM(self, request, context):
        """Calculate ICM equity for tournament players"""
        raise NotImplementedError("Implement in subclass")

    def GetICMForSpot(self, request, context):
        """Get ICM-adjusted recommendation for a push/fold spot"""
        raise NotImplementedError("Implement in subclass")

    def GetStrategy(self, request, context):
        """Get a GTO strategy by parameters"""
        raise NotImplementedError("Implement in subclass")

    def ListStrategies(self, request, context):
        """List stored strategies with optional filters"""
        raise NotImplementedError("Implement in subclass")

    def StreamProgress(self, request, context):
        """Stream progress updates for a solve job (async generator)"""
        raise NotImplementedError("Implement in subclass")


def add_SolverServicer_to_server(servicer, server):
    """Add servicer to gRPC server - callable signature matching grpc server"""
    pass  # Handled in service.py
