# Generated gRPC service stubs
# This module would normally be generated by grpc_tools.protoc

import grpc

class SolverServicer:
    """Servicer class for Solver service - implement SubmitSolve and GetSolveStatus"""
    
    def __init__(self):
        pass
    
    def SubmitSolve(self, request, context):
        """Submit a new solve job"""
        raise NotImplementedError("Implement in subclass")
    
    def GetSolveStatus(self, request, context):
        """Get the status of a solve job"""
        raise NotImplementedError("Implement in subclass")


def add_SolverServicer_to_server(servicer, server):
    """Add servicer to gRPC server - callable signature matching grpc server"""
    pass  # Handled in service.py
