"""
Seed data for quiz spots - 50+ NLH spots covering various categories and difficulties.

Run with: python -m apps.api.prisma.seed
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

from apps.api.services.database import engine, Base
from apps.api.services.quiz_models import QuizSpot
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

# 50+ quiz spots covering different poker situations
SEED_SPOTS = [
    # === PREFLOP: 3-BET POTS ===
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "AA",
        "board": None,
        "pot_size": 60,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.95,
        "gto_ev": 2.15,
        "options": [
            {"action": "raise", "ev": 2.15, "frequency": 0.95},
            {"action": "call", "ev": 1.80, "frequency": 0.04},
            {"action": "fold", "ev": 0, "frequency": 0.01},
        ],
        "explanation": "AA is a premium hand that wants to build pots and extract value. 3-bet pot with deep stacks - raise for value.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "KK",
        "board": None,
        "pot_size": 60,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.93,
        "gto_ev": 2.00,
        "options": [
            {"action": "raise", "ev": 2.00, "frequency": 0.93},
            {"action": "call", "ev": 1.65, "frequency": 0.05},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "KK is also a premium hand. In 3-bet pots, raising is standard to build the pot and narrow the field.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "intermediate",
        "position": "CO",
        "hero_hand": "AKs",
        "board": None,
        "pot_size": 55,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.88,
        "gto_ev": 1.75,
        "options": [
            {"action": "raise", "ev": 1.75, "frequency": 0.88},
            {"action": "call", "ev": 1.45, "frequency": 0.10},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "AKs (suited connectors) is a strong hand that benefits from playing big pots. 3-bet to isolate and build value.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "intermediate",
        "position": "SB",
        "hero_hand": "QQ",
        "board": None,
        "pot_size": 65,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.85,
        "gto_ev": 1.60,
        "options": [
            {"action": "raise", "ev": 1.60, "frequency": 0.85},
            {"action": "call", "ev": 1.30, "frequency": 0.12},
            {"action": "fold", "ev": 0, "frequency": 0.03},
        ],
        "explanation": "QQ is a strong hand but faces more resistance from BTN and CO ranges. 3-bet for value but be prepared for 4-bet scenarios.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "advanced",
        "position": "BB",
        "hero_hand": "JTs",
        "board": None,
        "pot_size": 70,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.55,
        "gto_ev": 0.45,
        "options": [
            {"action": "raise", "ev": 0.30, "frequency": 0.25},
            {"action": "call", "ev": 0.45, "frequency": 0.55},
            {"action": "fold", "ev": 0, "frequency": 0.20},
        ],
        "explanation": "JTs in a 3-bet pot vs BTN opens - suited connectors have good implied odds but need to be selective. Calling is often best to realize equity.",
        "street": "preflop",
    },
    # === PREFLOP: OPEN-RAISE POTS ===
    {
        "game_type": "nlh",
        "category": "open-raise pot",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "AKo",
        "board": None,
        "pot_size": 40,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.90,
        "gto_ev": 1.85,
        "options": [
            {"action": "raise", "ev": 1.85, "frequency": 0.90},
            {"action": "call", "ev": 1.50, "frequency": 0.08},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "AKo (offsuit) is a premium hand from BTN. Open-raising to build pots and apply pressure to the blinds.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "open-raise pot",
        "difficulty": "beginner",
        "position": "CO",
        "hero_hand": "AQs",
        "board": None,
        "pot_size": 40,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.88,
        "gto_ev": 1.70,
        "options": [
            {"action": "raise", "ev": 1.70, "frequency": 0.88},
            {"action": "call", "ev": 1.35, "frequency": 0.10},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "AQs is a strong hand from CO. Open-raising to apply pressure to the button and blinds.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "open-raise pot",
        "difficulty": "intermediate",
        "position": "UTG",
        "hero_hand": "TT",
        "board": None,
        "pot_size": 40,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.75,
        "gto_ev": 1.25,
        "options": [
            {"action": "raise", "ev": 1.25, "frequency": 0.75},
            {"action": "call", "ev": 1.00, "frequency": 0.20},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "TT (pocket tens) from UTG - strong but faces resistance. Raise for value but be ready to fold to 4-bets.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "open-raise pot",
        "difficulty": "intermediate",
        "position": "MP",
        "hero_hand": "KQs",
        "board": None,
        "pot_size": 40,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.70,
        "gto_ev": 1.10,
        "options": [
            {"action": "raise", "ev": 1.10, "frequency": 0.70},
            {"action": "call", "ev": 0.85, "frequency": 0.25},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "KQs suited connectors have good playability but need to be careful from early positions.",
        "street": "preflop",
    },
    {
        "game_type": "nlh",
        "category": "open-raise pot",
        "difficulty": "advanced",
        "position": "SB",
        "hero_hand": "A5s",
        "board": None,
        "pot_size": 40,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.45,
        "gto_ev": 0.25,
        "options": [
            {"action": "raise", "ev": 0.15, "frequency": 0.35},
            {"action": "call", "ev": 0.25, "frequency": 0.45},
            {"action": "fold", "ev": 0, "frequency": 0.20},
        ],
        "explanation": "A5s from SB vs BTN open - the BTN range is strong so we need to be selective. Sometimes it's a fold, sometimes a call.",
        "street": "preflop",
    },
    # === FLOP: OVERCARD ON BOARD ===
    {
        "game_type": "nlh",
        "category": "overcard board",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "KK",
        "board": "AKr",
        "pot_size": 80,
        "stack_depth": 150,
        "gto_action": "call",
        "gto_frequency": 0.80,
        "gto_ev": 1.20,
        "options": [
            {"action": "raise", "ev": 1.10, "frequency": 0.15},
            {"action": "call", "ev": 1.20, "frequency": 0.80},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "KK on an Ace-high board - we have second pair but face many Ax hands. Calling allows us to see if we can get value from worse hands.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "overcard board",
        "difficulty": "intermediate",
        "position": "CO",
        "hero_hand": "QQ",
        "board": "AKr",
        "pot_size": 90,
        "stack_depth": 120,
        "gto_action": "call",
        "gto_frequency": 0.65,
        "gto_ev": 0.85,
        "options": [
            {"action": "raise", "ev": 0.70, "frequency": 0.25},
            {"action": "call", "ev": 0.85, "frequency": 0.65},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "QQ on AK-high board - 'the worst case scenario' for QQ. Checking/calling is standard. The board hits our opponent's range heavily.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "overcard board",
        "difficulty": "advanced",
        "position": "BB",
        "hero_hand": "ATs",
        "board": "KQr",
        "pot_size": 75,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.55,
        "gto_ev": -0.10,
        "options": [
            {"action": "raise", "ev": -0.35, "frequency": 0.25},
            {"action": "call", "ev": -0.05, "frequency": 0.20},
            {"action": "fold", "ev": -0.10, "frequency": 0.55},
        ],
        "explanation": "ATs on K-Q-high board facing a bet - we have no pair and face a strong range. The board coordinates heavily with opponent's range.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "overcard board",
        "difficulty": "advanced",
        "position": "SB",
        "hero_hand": "JJ",
        "board": "AQr",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.60,
        "gto_ev": 0.65,
        "options": [
            {"action": "raise", "ev": 0.50, "frequency": 0.30},
            {"action": "call", "ev": 0.65, "frequency": 0.60},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "JJ on AQ-high board - pocket jacks are vulnerable but we have showdown value. Calling is often best to see turn cards that might help.",
        "street": "flop",
    },
    # === FLOP: MONOBOARD ===
    {
        "game_type": "nlh",
        "category": "monoboard",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "AA",
        "board": "9s9h9d",
        "pot_size": 100,
        "stack_depth": 150,
        "gto_action": "raise",
        "gto_frequency": 0.95,
        "gto_ev": 2.50,
        "options": [
            {"action": "raise", "ev": 2.50, "frequency": 0.95},
            {"action": "call", "ev": 2.00, "frequency": 0.04},
            {"action": "fold", "ev": 0, "frequency": 0.01},
        ],
        "explanation": "Set of nines on a monotone board - we have the absolute nuts! Raising builds the pot for maximum value.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "monoboard",
        "difficulty": "intermediate",
        "position": "BB",
        "hero_hand": "KJs",
        "board": "Qs Js Ts",
        "pot_size": 80,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.55,
        "gto_ev": 0.70,
        "options": [
            {"action": "raise", "ev": 0.55, "frequency": 0.30},
            {"action": "call", "ev": 0.70, "frequency": 0.55},
            {"action": "fold", "ev": 0, "frequency": 0.15},
        ],
        "explanation": "Nuts flush draw on monotone board - checking/calling is standard to realize equity. Raising folds out better hands but we want to see cards cheaply.",
        "street": "flop",
    },
    # === FLOP: PAIRED BOARD ===
    {
        "game_type": "nlh",
        "category": "paired board",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "66",
        "board": "KcKhKd",
        "pot_size": 90,
        "stack_depth": 120,
        "gto_action": "call",
        "gto_frequency": 0.70,
        "gto_ev": 0.80,
        "options": [
            {"action": "raise", "ev": 0.60, "frequency": 0.20},
            {"action": "call", "ev": 0.80, "frequency": 0.70},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Bottom set on a paired Kings board - we have a strong made hand but one of the few combos that can have us dominated. Calling is safe.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "paired board",
        "difficulty": "intermediate",
        "position": "CO",
        "hero_hand": "AA",
        "board": "QQr",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.85,
        "gto_ev": 1.50,
        "options": [
            {"action": "raise", "ev": 1.50, "frequency": 0.85},
            {"action": "call", "ev": 1.20, "frequency": 0.12},
            {"action": "fold", "ev": 0, "frequency": 0.03},
        ],
        "explanation": "Top set on paired Queen board - absolute monster. Raise for value to thin the field and build the pot.",
        "street": "flop",
    },
    # === FLOP: WET BOARD ===
    {
        "game_type": "nlh",
        "category": "wet board",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "78s",
        "board": "9TsQh",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.60,
        "gto_ev": 0.55,
        "options": [
            {"action": "raise", "ev": 0.35, "frequency": 0.25},
            {"action": "call", "ev": 0.55, "frequency": 0.60},
            {"action": "fold", "ev": 0, "frequency": 0.15},
        ],
        "explanation": "Open-ended straight draw + flush draw on a very wet board. Checking/calling realizes our huge equity cheaply. Raising is thin.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "wet board",
        "difficulty": "advanced",
        "position": "BB",
        "hero_hand": "TT",
        "board": "JTsQh",
        "pot_size": 95,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.50,
        "gto_ev": -0.20,
        "options": [
            {"action": "raise", "ev": 0.10, "frequency": 0.30},
            {"action": "call", "ev": -0.05, "frequency": 0.20},
            {"action": "fold", "ev": -0.20, "frequency": 0.50},
        ],
        "explanation": "Gutshot straight draw on a very wet coordinated board. Facing aggression, our hand is often dominated and we should fold.",
        "street": "flop",
    },
    # === TURN: OVERCARD ===
    {
        "game_type": "nlh",
        "category": "overcard on board",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "KK",
        "board": "AJr4c",
        "turn": "K",
        "pot_size": 100,
        "stack_depth": 120,
        "gto_action": "raise",
        "gto_frequency": 0.88,
        "gto_ev": 1.80,
        "options": [
            {"action": "raise", "ev": 1.80, "frequency": 0.88},
            {"action": "call", "ev": 1.45, "frequency": 0.10},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "KK turns top two pair on Ace-high board - we want to get value from worse hands. Raising is standard.",
        "street": "turn",
    },
    {
        "game_type": "nlh",
        "category": "overcard on board",
        "difficulty": "advanced",
        "position": "CO",
        "hero_hand": "QQ",
        "board": "KQr4c",
        "turn": "A",
        "pot_size": 90,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.60,
        "gto_ev": 0.75,
        "options": [
            {"action": "raise", "ev": 0.55, "frequency": 0.30},
            {"action": "call", "ev": 0.75, "frequency": 0.60},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "QQ faces an Ace on the turn on K-Q-high board. Top pair but very scary card. Checking/calling is often best.",
        "street": "turn",
    },
    # === TURN: STRAIGHT COMPLETED ===
    {
        "game_type": "nlh",
        "category": "straight completed",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "45s",
        "board": "236r",
        "turn": "7",
        "pot_size": 75,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.75,
        "gto_ev": 1.20,
        "options": [
            {"action": "raise", "ev": 1.20, "frequency": 0.75},
            {"action": "call", "ev": 0.90, "frequency": 0.20},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "Open-ended straight completed on the turn. We have the nuts or near-nuts. Value betting is standard.",
        "street": "turn",
    },
    {
        "game_type": "nlh",
        "category": "straight completed",
        "difficulty": "advanced",
        "position": "BB",
        "hero_hand": "T9",
        "board": "JQr",
        "turn": "K",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.50,
        "gto_ev": -0.15,
        "options": [
            {"action": "raise", "ev": 0.20, "frequency": 0.35},
            {"action": "call", "ev": -0.05, "frequency": 0.15},
            {"action": "fold", "ev": -0.15, "frequency": 0.50},
        ],
        "explanation": "Broadway straight on a Q-J-high board, King completes. Facing a bet, we need to be careful of boats and better straights.",
        "street": "turn",
    },
    # === TURN: FLUSH COMPLETED ===
    {
        "game_type": "nlh",
        "category": "flush completed",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "AsQs",
        "board": "KsJh2h",
        "turn": "6h",
        "pot_size": 95,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.82,
        "gto_ev": 1.60,
        "options": [
            {"action": "raise", "ev": 1.60, "frequency": 0.82},
            {"action": "call", "ev": 1.25, "frequency": 0.15},
            {"action": "fold", "ev": 0, "frequency": 0.03},
        ],
        "explanation": "Flush completed on the turn with Ace-high flush. We have the second nuts (if Ace of hearts). Value betting is strong.",
        "street": "turn",
    },
    {
        "game_type": "nlh",
        "category": "flush completed",
        "difficulty": "advanced",
        "position": "CO",
        "hero_hand": "KcQc",
        "board": "AcJh3c",
        "turn": "8c",
        "pot_size": 80,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.45,
        "gto_ev": -0.25,
        "options": [
            {"action": "raise", "ev": 0.10, "frequency": 0.30},
            {"action": "call", "ev": -0.10, "frequency": 0.25},
            {"action": "fold", "ev": -0.25, "frequency": 0.45},
        ],
        "explanation": "Flush completed but middle flush facing a large bet on a board that could also give opponents a full house. Be cautious.",
        "street": "turn",
    },
    # === RIVER: VALUE ===
    {
        "game_type": "nlh",
        "category": "river value",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "AA",
        "board": "KQJr",
        "turn": "T",
        "river": "A",
        "pot_size": 120,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.90,
        "gto_ev": 2.00,
        "options": [
            {"action": "raise", "ev": 2.00, "frequency": 0.90},
            {"action": "call", "ev": 1.50, "frequency": 0.08},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "Top set on river - absolute monster. Value betting is standard. We want to get called by worse hands.",
        "street": "river",
    },
    {
        "game_type": "nlh",
        "category": "river value",
        "difficulty": "intermediate",
        "position": "CO",
        "hero_hand": "JJ",
        "board": "QqJs2c",
        "turn": "K",
        "river": "J",
        "pot_size": 100,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.85,
        "gto_ev": 1.70,
        "options": [
            {"action": "raise", "ev": 1.70, "frequency": 0.85},
            {"action": "call", "ev": 1.30, "frequency": 0.12},
            {"action": "fold", "ev": 0, "frequency": 0.03},
        ],
        "explanation": "Full house on river - the absolute nuts in most scenarios. Value bet BIG.",
        "street": "river",
    },
    # === RIVER: BLUFF CATCHING ===
    {
        "game_type": "nlh",
        "category": "river bluff catch",
        "difficulty": "intermediate",
        "position": "BB",
        "hero_hand": "AK",
        "board": "KQJr",
        "turn": "T",
        "river": "2",
        "pot_size": 80,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.55,
        "gto_ev": 0.60,
        "options": [
            {"action": "raise", "ev": 0.30, "frequency": 0.25},
            {"action": "call", "ev": 0.60, "frequency": 0.55},
            {"action": "fold", "ev": 0, "frequency": 0.20},
        ],
        "explanation": "Top pair on river - potential bluff catcher. Calling is often best to catch bluffs from opponent.",
        "street": "river",
    },
    {
        "game_type": "nlh",
        "category": "river bluff catch",
        "difficulty": "advanced",
        "position": "SB",
        "hero_hand": "88",
        "board": "JTsQr",
        "turn": "K",
        "river": "8",
        "pot_size": 90,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.50,
        "gto_ev": 0.45,
        "options": [
            {"action": "raise", "ev": 0.25, "frequency": 0.35},
            {"action": "call", "ev": 0.45, "frequency": 0.50},
            {"action": "fold", "ev": 0, "frequency": 0.15},
        ],
        "explanation": "Middle set on a very coordinated board - opponent's range is weighted toward value. Bluff catching is often the best option.",
        "street": "river",
    },
    # === RIVER: FACING BET ===
    {
        "game_type": "nlh",
        "category": "river facing bet",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "QQ",
        "board": "AKr4c",
        "turn": "J",
        "river": "Q",
        "pot_size": 110,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.88,
        "gto_ev": 1.90,
        "options": [
            {"action": "raise", "ev": 1.90, "frequency": 0.88},
            {"action": "call", "ev": 1.40, "frequency": 0.10},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "Trips on river - strong hand. Raise for value as opponents may have weaker hands like Ace-high or pair+draw.",
        "street": "river",
    },
    {
        "game_type": "nlh",
        "category": "river facing bet",
        "difficulty": "intermediate",
        "position": "CO",
        "hero_hand": "TT",
        "board": "J9s7c",
        "turn": "Q",
        "river": "T",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.62,
        "gto_ev": 0.70,
        "options": [
            {"action": "raise", "ev": 0.55, "frequency": 0.28},
            {"action": "call", "ev": 0.70, "frequency": 0.62},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Bottom trips on river. Calling is often better than raising to induce bluffs from opponents.",
        "street": "river",
    },
    {
        "game_type": "nlh",
        "category": "river facing bet",
        "difficulty": "advanced",
        "position": "BB",
        "hero_hand": "KQ",
        "board": "JTsQr",
        "turn": "K",
        "river": "A",
        "pot_size": 95,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.45,
        "gto_ev": 0.0,
        "options": [
            {"action": "raise", "ev": 0.15, "frequency": 0.30},
            {"action": "call", "ev": 0.05, "frequency": 0.25},
            {"action": "fold", "ev": 0.0, "frequency": 0.45},
        ],
        "explanation": "Two pair on a scary board - facing a bet, we're often beat by better two pair, straights, or sets. Folding is often correct.",
        "street": "river",
    },
    # === DEEP STACK ===
    {
        "game_type": "nlh",
        "category": "deep stack",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "AA",
        "board": "KsQdJh",
        "pot_size": 100,
        "stack_depth": 250,
        "gto_action": "raise",
        "gto_frequency": 0.92,
        "gto_ev": 3.50,
        "options": [
            {"action": "raise", "ev": 3.50, "frequency": 0.92},
            {"action": "call", "ev": 2.80, "frequency": 0.06},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "Deep stack scenario - top set on coordinated board. With 250bb stacks, raising is crucial to get value before the board gets scary.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "deep stack",
        "difficulty": "advanced",
        "position": "CO",
        "hero_hand": "JJ",
        "board": "AKr",
        "pot_size": 120,
        "stack_depth": 300,
        "gto_action": "call",
        "gto_frequency": 0.70,
        "gto_ev": 2.00,
        "options": [
            {"action": "raise", "ev": 1.50, "frequency": 0.20},
            {"action": "call", "ev": 2.00, "frequency": 0.70},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Deep stack with JJ on Ace-high board. With so many stacks behind, slowplaying with Calling is often best to keep opponents in the hand.",
        "street": "flop",
    },
    # === SHORT STACK (SPR < 3) ===
    {
        "game_type": "nlh",
        "category": "short stack",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "55",
        "board": "Ks9d",
        "pot_size": 80,
        "stack_depth": 30,
        "gto_action": "raise",
        "gto_frequency": 0.85,
        "gto_ev": 1.20,
        "options": [
            {"action": "raise", "ev": 1.20, "frequency": 0.85},
            {"action": "call", "ev": 0.80, "frequency": 0.12},
            {"action": "fold", "ev": 0, "frequency": 0.03},
        ],
        "explanation": "Short stacked (SPR ~1.5) with middle set. All-in or raising is standard - we want to get stacks in while we have the best hand.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "short stack",
        "difficulty": "intermediate",
        "position": "SB",
        "hero_hand": "AT",
        "board": "KQr",
        "pot_size": 60,
        "stack_depth": 40,
        "gto_action": "all-in",
        "gto_frequency": 0.75,
        "gto_ev": 1.10,
        "options": [
            {"action": "all-in", "ev": 1.10, "frequency": 0.75},
            {"action": "call", "ev": 0.60, "frequency": 0.15},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Short stack scenario with Ace-Ten on King-Queen-high board. With low SPR, going all-in is often the best play to maximize fold equity and value.",
        "street": "flop",
    },
    # === HEADS-UP POTS ===
    {
        "game_type": "nlh",
        "category": "heads-up",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "AA",
        "board": "KsQd",
        "pot_size": 100,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.95,
        "gto_ev": 2.20,
        "options": [
            {"action": "raise", "ev": 2.20, "frequency": 0.95},
            {"action": "call", "ev": 1.70, "frequency": 0.04},
            {"action": "fold", "ev": 0, "frequency": 0.01},
        ],
        "explanation": "Heads-up vs BB with AA on King-high flop. Raising is standard to build pots and apply pressure.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "heads-up",
        "difficulty": "intermediate",
        "position": "BB",
        "hero_hand": "77",
        "board": "JTs",
        "pot_size": 85,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.65,
        "gto_ev": 0.80,
        "options": [
            {"action": "raise", "ev": 0.60, "frequency": 0.25},
            {"action": "call", "ev": 0.80, "frequency": 0.65},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Heads-up defense with middle pair on a Jack-ten-high board. Checking/calling is standard to realize equity.",
        "street": "flop",
    },
    # === MULTIWAY POTS ===
    {
        "game_type": "nlh",
        "category": "multiway",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "KK",
        "board": "KsQdJh",
        "pot_size": 150,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.75,
        "gto_ev": 1.40,
        "options": [
            {"action": "raise", "ev": 1.20, "frequency": 0.20},
            {"action": "call", "ev": 1.40, "frequency": 0.75},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "Multiway pot with top set on coordinated board. With multiple opponents, slowplaying with calling is better to extract value.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "multiway",
        "difficulty": "advanced",
        "position": "CO",
        "hero_hand": "JJ",
        "board": "JTsQh",
        "pot_size": 160,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.50,
        "gto_ev": 0.90,
        "options": [
            {"action": "raise", "ev": 0.50, "frequency": 0.30},
            {"action": "call", "ev": 0.90, "frequency": 0.50},
            {"action": "fold", "ev": 0, "frequency": 0.20},
        ],
        "explanation": "Multiway with trips Jacks on a very coordinated board. Be careful of better hands. Checking/calling is often best in multiway.",
        "street": "flop",
    },
    # === 3-BET POTS (POSTFLOP) ===
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "intermediate",
        "position": "BTN",
        "hero_hand": "AA",
        "board": "KsQd",
        "pot_size": 120,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.90,
        "gto_ev": 2.50,
        "options": [
            {"action": "raise", "ev": 2.50, "frequency": 0.90},
            {"action": "call", "ev": 1.90, "frequency": 0.08},
            {"action": "fold", "ev": 0, "frequency": 0.02},
        ],
        "explanation": "3-bet pot heads-up with AA on King-high flop. Raise for value - we want to build the pot with our premium hand.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "3-bet pot",
        "difficulty": "advanced",
        "position": "SB",
        "hero_hand": "88",
        "board": "AKr",
        "pot_size": 110,
        "stack_depth": 100,
        "gto_action": "fold",
        "gto_frequency": 0.50,
        "gto_ev": 0.0,
        "options": [
            {"action": "raise", "ev": 0.20, "frequency": 0.30},
            {"action": "call", "ev": 0.05, "frequency": 0.20},
            {"action": "fold", "ev": 0.0, "frequency": 0.50},
        ],
        "explanation": "3-bet pot with middle pair facing a c-bet on Ace-high board. We're dominated by Ace-x and should often fold.",
        "street": "flop",
    },
    # === IP VS OOP ===
    {
        "game_type": "nlh",
        "category": "IP vs OOP",
        "difficulty": "beginner",
        "position": "BTN",
        "hero_hand": "TT",
        "board": "KJr",
        "pot_size": 70,
        "stack_depth": 100,
        "gto_action": "raise",
        "gto_frequency": 0.80,
        "gto_ev": 1.30,
        "options": [
            {"action": "raise", "ev": 1.30, "frequency": 0.80},
            {"action": "call", "ev": 1.00, "frequency": 0.15},
            {"action": "fold", "ev": 0, "frequency": 0.05},
        ],
        "explanation": "In position with pocket tens on King-high flop. Leverage position to raise and build pots.",
        "street": "flop",
    },
    {
        "game_type": "nlh",
        "category": "IP vs OOP",
        "difficulty": "intermediate",
        "position": "BB",
        "hero_hand": "QJs",
        "board": "JTsQ",
        "pot_size": 90,
        "stack_depth": 100,
        "gto_action": "call",
        "gto_frequency": 0.60,
        "gto_ev": 0.85,
        "options": [
            {"action": "raise", "ev": 0.65, "frequency": 0.30},
            {"action": "call", "ev": 0.85, "frequency": 0.60},
            {"action": "fold", "ev": 0, "frequency": 0.10},
        ],
        "explanation": "Out of position with top two pair on a Jack-high board. Checking/calling allows us to see cheap cards and extract value.",
        "street": "flop",
    },
]


async def seed_quiz_spots():
    """Seed the database with quiz spots."""
    async with AsyncSession(engine) as session:
        # Create tables if they don't exist (use proper schema from model)
        async with engine.begin() as conn:
            from apps.api.services.quiz_models import QuizSpot, Base as QuizBase
            from sqlalchemy import MetaData

            # Try to create quiz_spots with proper columns
            try:
                await conn.run_sync(QuizSpot.metadata.create_all, checkfirst=True)
            except Exception:
                pass

        # Check if spots already exist
        result = await session.execute(text("SELECT COUNT(*) FROM quiz_spots"))
        count = result.scalar()

        if count > 0:
            print(f"Quiz spots already exist ({count} spots). Skipping seed.")
            return

        # Insert seed spots
        for spot_data in SEED_SPOTS:
            spot = QuizSpot(
                game_type=spot_data["game_type"],
                category=spot_data["category"],
                difficulty=spot_data["difficulty"],
                position=spot_data["position"],
                hero_hand=spot_data["hero_hand"],
                board=spot_data.get("board"),
                turn=spot_data.get("turn"),
                river=spot_data.get("river"),
                pot_size=spot_data["pot_size"],
                stack_depth=spot_data["stack_depth"],
                gto_action=spot_data["gto_action"],
                gto_frequency=spot_data["gto_frequency"],
                gto_ev=spot_data["gto_ev"],
                options=spot_data["options"],
                explanation=spot_data.get("explanation", ""),
                street=spot_data["street"],
            )
            session.add(spot)

        await session.commit()
        print(f"Seeded {len(SEED_SPOTS)} quiz spots.")


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed_quiz_spots())
