# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import solver_pb2 as solver__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in solver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolverServiceStub(object):
    """============== Services ==============

    Main solver service for GTO poker calculations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSolve = channel.unary_unary(
                '/solver.SolverService/SubmitSolve',
                request_serializer=solver__pb2.SolveRequest.SerializeToString,
                response_deserializer=solver__pb2.SolveResponse.FromString,
                _registered_method=True)
        self.GetSolveStatus = channel.unary_unary(
                '/solver.SolverService/GetSolveStatus',
                request_serializer=solver__pb2.SolveRequest.SerializeToString,
                response_deserializer=solver__pb2.SolveResponse.FromString,
                _registered_method=True)
        self.GetSolveResults = channel.unary_unary(
                '/solver.SolverService/GetSolveResults',
                request_serializer=solver__pb2.SolveRequest.SerializeToString,
                response_deserializer=solver__pb2.SolveResponse.FromString,
                _registered_method=True)
        self.CalculateICM = channel.unary_unary(
                '/solver.SolverService/CalculateICM',
                request_serializer=solver__pb2.ICMRequest.SerializeToString,
                response_deserializer=solver__pb2.ICMResponse.FromString,
                _registered_method=True)
        self.GetICMForSpot = channel.unary_unary(
                '/solver.SolverService/GetICMForSpot',
                request_serializer=solver__pb2.ICMSpotRequest.SerializeToString,
                response_deserializer=solver__pb2.ICMSpotResponse.FromString,
                _registered_method=True)
        self.GetStrategy = channel.unary_unary(
                '/solver.SolverService/GetStrategy',
                request_serializer=solver__pb2.GetStrategyRequest.SerializeToString,
                response_deserializer=solver__pb2.GetStrategyResponse.FromString,
                _registered_method=True)
        self.ListStrategies = channel.unary_unary(
                '/solver.SolverService/ListStrategies',
                request_serializer=solver__pb2.ListStrategiesRequest.SerializeToString,
                response_deserializer=solver__pb2.ListStrategiesResponse.FromString,
                _registered_method=True)
        self.DeleteStrategy = channel.unary_unary(
                '/solver.SolverService/DeleteStrategy',
                request_serializer=solver__pb2.GetStrategyRequest.SerializeToString,
                response_deserializer=solver__pb2.GetStrategyResponse.FromString,
                _registered_method=True)
        self.StreamProgress = channel.unary_stream(
                '/solver.SolverService/StreamProgress',
                request_serializer=solver__pb2.SolveRequest.SerializeToString,
                response_deserializer=solver__pb2.ProgressUpdate.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/solver.SolverService/HealthCheck',
                request_serializer=solver__pb2.HealthRequest.SerializeToString,
                response_deserializer=solver__pb2.HealthResponse.FromString,
                _registered_method=True)


class SolverServiceServicer(object):
    """============== Services ==============

    Main solver service for GTO poker calculations
    """

    def SubmitSolve(self, request, context):
        """Submit a new solve job (synchronous response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSolveStatus(self, request, context):
        """Get the status of a solve job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSolveResults(self, request, context):
        """Get solve results including computed strategy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateICM(self, request, context):
        """Calculate ICM equity for tournament players
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetICMForSpot(self, request, context):
        """Get ICM-adjusted recommendation for a push/fold spot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategy(self, request, context):
        """Get a GTO strategy by parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategies(self, request, context):
        """List stored strategies with optional filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStrategy(self, request, context):
        """Delete a stored strategy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProgress(self, request, context):
        """Stream progress updates for a solve job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitSolve': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSolve,
                    request_deserializer=solver__pb2.SolveRequest.FromString,
                    response_serializer=solver__pb2.SolveResponse.SerializeToString,
            ),
            'GetSolveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSolveStatus,
                    request_deserializer=solver__pb2.SolveRequest.FromString,
                    response_serializer=solver__pb2.SolveResponse.SerializeToString,
            ),
            'GetSolveResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSolveResults,
                    request_deserializer=solver__pb2.SolveRequest.FromString,
                    response_serializer=solver__pb2.SolveResponse.SerializeToString,
            ),
            'CalculateICM': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateICM,
                    request_deserializer=solver__pb2.ICMRequest.FromString,
                    response_serializer=solver__pb2.ICMResponse.SerializeToString,
            ),
            'GetICMForSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetICMForSpot,
                    request_deserializer=solver__pb2.ICMSpotRequest.FromString,
                    response_serializer=solver__pb2.ICMSpotResponse.SerializeToString,
            ),
            'GetStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategy,
                    request_deserializer=solver__pb2.GetStrategyRequest.FromString,
                    response_serializer=solver__pb2.GetStrategyResponse.SerializeToString,
            ),
            'ListStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategies,
                    request_deserializer=solver__pb2.ListStrategiesRequest.FromString,
                    response_serializer=solver__pb2.ListStrategiesResponse.SerializeToString,
            ),
            'DeleteStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStrategy,
                    request_deserializer=solver__pb2.GetStrategyRequest.FromString,
                    response_serializer=solver__pb2.GetStrategyResponse.SerializeToString,
            ),
            'StreamProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProgress,
                    request_deserializer=solver__pb2.SolveRequest.FromString,
                    response_serializer=solver__pb2.ProgressUpdate.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=solver__pb2.HealthRequest.FromString,
                    response_serializer=solver__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'solver.SolverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('solver.SolverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolverService(object):
    """============== Services ==============

    Main solver service for GTO poker calculations
    """

    @staticmethod
    def SubmitSolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/SubmitSolve',
            solver__pb2.SolveRequest.SerializeToString,
            solver__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSolveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/GetSolveStatus',
            solver__pb2.SolveRequest.SerializeToString,
            solver__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSolveResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/GetSolveResults',
            solver__pb2.SolveRequest.SerializeToString,
            solver__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateICM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/CalculateICM',
            solver__pb2.ICMRequest.SerializeToString,
            solver__pb2.ICMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetICMForSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/GetICMForSpot',
            solver__pb2.ICMSpotRequest.SerializeToString,
            solver__pb2.ICMSpotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/GetStrategy',
            solver__pb2.GetStrategyRequest.SerializeToString,
            solver__pb2.GetStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/ListStrategies',
            solver__pb2.ListStrategiesRequest.SerializeToString,
            solver__pb2.ListStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/DeleteStrategy',
            solver__pb2.GetStrategyRequest.SerializeToString,
            solver__pb2.GetStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/solver.SolverService/StreamProgress',
            solver__pb2.SolveRequest.SerializeToString,
            solver__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solver.SolverService/HealthCheck',
            solver__pb2.HealthRequest.SerializeToString,
            solver__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
